on:
  push:
    branches: [ main ]

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # get repo
    - uses: azure/login@v2 # log into Azure with managed identity
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }} 
        tenant-id: ${{ secrets.AZURE_TENANT_ID }} 
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/sql-action@v2 # build and publish dacpac
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }} # this string does not contain a password
        path: './ProgressVisualiserSql.sqlproj'
        action: 'Publish'
        build-arguments: '-c Release'
    - name: logout # log out of Azure
      run: |
        az logout