on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs: # allow manual trigger
      environment:
        type: environment
        description: 'Environment to deploy to'
        required: true

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4 # get repo
    - uses: azure/sql-action@v2 # build and publish dacpac
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './ProgressVisualiserSql.sqlproj'
        action: 'Publish'
        build-arguments: '-c Release'